### ISSUE TITLE
agregar opción en el dashboard admin para volver al home

### ISSUE THREAD

**Issue by juancruzroldan95** [fspiritosi/gym-go#143]
Pondría un link a "Volver a Home" con un iconito de flecha de retorno de material o algo por el estilo arriba a la derecha.

No entiendo bien el alcance de esta search bar fija ahí. Luego sacaría los botincitos de la campanita, la ruedita y el icono de perfil si es que no van a tener utilidad.

![image](https://github.com/fspiritosi/gym-go/assets/110354500/f0dab1ce-cd09-469d-9c0c-680e839769be)

**Comment by fspiritosi** [comment]
Resuelta.

Se modificó el Topbar. Se adjunta imagen. Rama que modifica: fix_dashboardAdmin_01

![image](https://github.com/fspiritosi/gym-go/assets/35983630/849d38f6-3eee-4ce9-a479-3604001f34a6)
